### ISSUE TITLE
Lazily construct the Injector in JerseyGuiceServletContextListener so that modules can be added at runtime

### ISSUE THREAD

**Issue by sdahlberg** [Squarespace/jersey2-guice#33]
Currently we still use JAX-WS (next to JAX-RS) and let the endpoint instances be resolved by guice. This is done by subclassing `com.sun.xml.ws.server.AbstractMultiInstanceResolver` and implement the resolve and start methods. In the start method we register the webServiceContext instance binding as a guice module.

Unfortunately the guice injector in `JerseyGuiceServletContextListener` is created in the constructor. Would it be an option to create it lazily?

**Comment by rkapsi** [comment]
Hello,

sorry for the long no-response. I've just pushed a much more robust implementation to Maven Central. There are some little API changes and I ended up removing JerseyGuiceServletContextListener due to uncertainties if it could ever work.

There is basically a race condition in the Servlet container/Jersey/HK2 and the Web Application (i.e. everyone's code) that determines if a guicified ServiceLocator or a default ServiceLocator will be used. The only way to ensure it's Guice is to initialize the hooks as early and as eagerly as possible.

We run our code from `main()` methods and don't use any `ServletContextListener` at all.
